import React from "react";
import Head from "next/head";

import { Home } from "../presentation/pages";

export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Home />
    </>
  );
}
